//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeChannelViewJob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class youtubeEntities : DbContext
    {
        public youtubeEntities()
            : base("name=youtubeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Channel> Channels { get; set; }
        public DbSet<Video_NumberCount_History> Video_NumberCount_History { get; set; }
        public DbSet<Video> Videos { get; set; }
    
        public virtual ObjectResult<yt_Get_Channel_Result> yt_Get_Channel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<yt_Get_Channel_Result>("yt_Get_Channel");
        }
    
        public virtual int yt_Save_Video(string channelId, string videoEncryptedId, string videoTitle, string videoImageUrl, ObjectParameter id)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var videoEncryptedIdParameter = videoEncryptedId != null ?
                new ObjectParameter("VideoEncryptedId", videoEncryptedId) :
                new ObjectParameter("VideoEncryptedId", typeof(string));
    
            var videoTitleParameter = videoTitle != null ?
                new ObjectParameter("VideoTitle", videoTitle) :
                new ObjectParameter("VideoTitle", typeof(string));
    
            var videoImageUrlParameter = videoImageUrl != null ?
                new ObjectParameter("VideoImageUrl", videoImageUrl) :
                new ObjectParameter("VideoImageUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("yt_Save_Video", channelIdParameter, videoEncryptedIdParameter, videoTitleParameter, videoImageUrlParameter, id);
        }
    }
}
