//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeChannelViewJob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_NumberCount_History
    {
        public int Id { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<long> LikeCount { get; set; }
        public Nullable<long> DislikeCount { get; set; }
        public Nullable<long> FavouriteCount { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
